#!/bin/bash
;`
#####################################################################
# Notes
#####################################################################
;`
[NOTES]
notes: Chapter 2: Rational Agents
    #################################################################
    # Review
    #################################################################
    Hans Moravec, remember his paradox
    Two Brain Systems?
        Thinking Fast and Thinking Slow @(Daniel Kahneman)
        """System 1""": Fast, automatic, subconcios, emotional,
            Processing faces
            Detect hostility on a face or in a voice
            Orient the source of a sudden sound
            Answer 2+2
            Read words on large billboards
            Drive on an empty road
        """System 2""": Slow, effortful, logical, calculating, concious
            Focus on the voice of a particular person in a crowded and noisy room
            Search memory to identify a melody
            Count the occurrencess of the letter 'a' on a page
            compare 2 washing machines for overall value
            Fill out a tax form
            Check the validity of a complex logical argument

;`
#####################################################################
# Vocabulary
#####################################################################
;`
[VOCABULARY]

;`
#####################################################################
# Timeline
#####################################################################
;`
[TIMELINE]

